on "windows" {
    pub WS_TILED : DWORD : WS_OVERLAPPED
    pub WS_OVERLAPPEDWINDOW : DWORD : WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_THICKFRAME | WS_MINIMIZEBOX | WS_MAXIMIZEBOX
}
¬
on "windows" {

    pub WS_TILED            : DWORD : WS_OVERLAPPED
    pub WS_OVERLAPPEDWINDOW : DWORD :
                                      WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_THICKFRAME | WS_MINIMIZEBOX | WS_MAXIMIZEBOX

}
