//------------------------------------------------------------------------------
// Shared editor metadata for compiler-provided callables
//
// Copyright (C)2026 Matt Davies, all rights reserved
//------------------------------------------------------------------------------

#include <lsp/lsp.h>

internal const LspBuiltinCallable lsp_builtin_callables[] = {
    {LSP_BUILTIN_CALLABLE_DYNAMIC_ARRAY,
     "push",
     "push :: fn (value: T) -> void",
     "push(value: T) -> void",
     "Appends one value to the end of the dynamic array, growing its storage "
     "if needed.",
     1,
     {"value: T"}},
    {LSP_BUILTIN_CALLABLE_DYNAMIC_ARRAY,
     "append",
     "append :: fn (values: []T) -> void",
     "append(values: []T) -> void",
     "Appends every value from a matching slice or dynamic array.",
     1,
     {"values: []T"}},
    {LSP_BUILTIN_CALLABLE_DYNAMIC_ARRAY,
     "reserve_to",
     "reserve_to :: fn (capacity: usize) -> void",
     "reserve_to(capacity: usize) -> void",
     "Ensures the dynamic array can hold at least the requested absolute "
     "capacity.",
     1,
     {"capacity: usize"}},
    {LSP_BUILTIN_CALLABLE_DYNAMIC_ARRAY,
     "reserve_extra",
     "reserve_extra :: fn (additional: usize) -> void",
     "reserve_extra(additional: usize) -> void",
     "Ensures room for the requested number of additional live values.",
     1,
     {"additional: usize"}},
    {LSP_BUILTIN_CALLABLE_DYNAMIC_ARRAY,
     "resize_to",
     "resize_to :: fn (count: usize) -> void",
     "resize_to(count: usize) -> void",
     "Changes the live count and default-initialises any newly added values.",
     1,
     {"count: usize"}},
    {LSP_BUILTIN_CALLABLE_DYNAMIC_ARRAY,
     "resize_undefined_to",
     "resize_undefined_to :: fn (count: usize) -> void",
     "resize_undefined_to(count: usize) -> void",
     "Changes the live count without initialising newly added values.",
     1,
     {"count: usize"}},
    {LSP_BUILTIN_CALLABLE_DYNAMIC_ARRAY,
     "extend",
     "extend :: fn (count: usize) -> void",
     "extend(count: usize) -> void",
     "Adds the requested number of default-initialised values.",
     1,
     {"count: usize"}},
    {LSP_BUILTIN_CALLABLE_DYNAMIC_ARRAY,
     "extend_undefined",
     "extend_undefined :: fn (count: usize) -> void",
     "extend_undefined(count: usize) -> void",
     "Adds the requested number of uninitialised values.",
     1,
     {"count: usize"}},
    {LSP_BUILTIN_CALLABLE_DYNAMIC_ARRAY,
     "delete",
     "delete :: fn (index: usize) -> void",
     "delete(index: usize) -> void",
     "Removes the value at an index and shifts later values to preserve order.",
     1,
     {"index: usize"}},
    {LSP_BUILTIN_CALLABLE_DYNAMIC_ARRAY,
     "swap_delete",
     "swap_delete :: fn (index: usize) -> void",
     "swap_delete(index: usize) -> void",
     "Removes the value at an index by replacing it with the final value; "
     "order is not preserved.",
     1,
     {"index: usize"}},
    {LSP_BUILTIN_CALLABLE_DYNAMIC_ARRAY,
     "pop",
     "pop :: fn () -> T",
     "pop() -> T",
     "Removes and returns the final value. Popping an empty array is a runtime "
     "error.",
     0,
     {0}},
    {LSP_BUILTIN_CALLABLE_DYNAMIC_ARRAY,
     "clear",
     "clear :: fn () -> void",
     "clear() -> void",
     "Sets the live count to zero while retaining allocated capacity.",
     0,
     {0}},
    {LSP_BUILTIN_CALLABLE_DYNAMIC_ARRAY,
     "free",
     "free :: fn () -> void",
     "free() -> void",
     "Releases owned storage and resets the dynamic array to nil.",
     0,
     {0}},

    {LSP_BUILTIN_CALLABLE_ARENA,
     "alloc",
     "alloc :: fn [T] () -> ^T",
     "alloc[T]() -> ^T",
     "Allocates one naturally aligned value of type T from the arena.",
     0,
     {0}},
    {LSP_BUILTIN_CALLABLE_ARENA,
     "alloc_array",
     "alloc_array :: fn [T] (count: usize) -> []T",
     "alloc_array[T](count: usize) -> []T",
     "Allocates a contiguous slice of count naturally aligned T values from "
     "the arena.",
     1,
     {"count: usize"}},
    {LSP_BUILTIN_CALLABLE_ARENA,
     "alloc_bytes",
     "alloc_bytes :: fn (count: usize) -> []u8",
     "alloc_bytes(count: usize) -> []u8",
     "Allocates count bytes from the arena.",
     1,
     {"count: usize"}},
    {LSP_BUILTIN_CALLABLE_ARENA,
     "reset",
     "reset :: fn () -> void",
     "reset() -> void",
     "Invalidates all allocations from the arena while retaining its storage "
     "for reuse.",
     0,
     {0}},
    {LSP_BUILTIN_CALLABLE_ARENA,
     "mark",
     "mark :: fn () -> u32",
     "mark() -> u32",
     "Returns the current arena cursor for a later restore operation.",
     0,
     {0}},
    {LSP_BUILTIN_CALLABLE_ARENA,
     "restore",
     "restore :: fn (mark: u32) -> void",
     "restore(mark: u32) -> void",
     "Restores an earlier cursor and invalidates allocations made after that "
     "mark.",
     1,
     {"mark: u32"}},
    {LSP_BUILTIN_CALLABLE_ARENA,
     "done",
     "done :: fn () -> void",
     "done() -> void",
     "Releases the arena's reserved storage.",
     0,
     {0}},

    {LSP_BUILTIN_CALLABLE_ATOMIC,
     "load",
     "load :: fn (order :: AtomicLoadOrder = SequentiallyConsistent) -> T",
     "load(order :: AtomicLoadOrder = SequentiallyConsistent) -> T",
     "Loads the current value using the selected compile-time memory order.",
     1,
     {"order :: AtomicLoadOrder = SequentiallyConsistent"}},
    {LSP_BUILTIN_CALLABLE_ATOMIC,
     "store",
     "store :: fn (value: T, order :: AtomicStoreOrder = "
     "SequentiallyConsistent) -> void",
     "store(value: T, order :: AtomicStoreOrder = SequentiallyConsistent) -> "
     "void",
     "Stores a value using the selected compile-time memory order.",
     2,
     {"value: T", "order :: AtomicStoreOrder = SequentiallyConsistent"}},
    {LSP_BUILTIN_CALLABLE_ATOMIC,
     "exchange",
     "exchange :: fn (value: T, order :: AtomicOrder = SequentiallyConsistent) "
     "-> T",
     "exchange(value: T, order :: AtomicOrder = SequentiallyConsistent) -> T",
     "Atomically replaces the value and returns the previous value.",
     2,
     {"value: T", "order :: AtomicOrder = SequentiallyConsistent"}},
    {LSP_BUILTIN_CALLABLE_ATOMIC,
     "fetch_add",
     "fetch_add :: fn (value: T, order :: AtomicOrder = "
     "SequentiallyConsistent) -> T",
     "fetch_add(value: T, order :: AtomicOrder = SequentiallyConsistent) -> T",
     "Atomically adds a value and returns the previous value.",
     2,
     {"value: T", "order :: AtomicOrder = SequentiallyConsistent"}},
    {LSP_BUILTIN_CALLABLE_ATOMIC,
     "fetch_sub",
     "fetch_sub :: fn (value: T, order :: AtomicOrder = "
     "SequentiallyConsistent) -> T",
     "fetch_sub(value: T, order :: AtomicOrder = SequentiallyConsistent) -> T",
     "Atomically subtracts a value and returns the previous value.",
     2,
     {"value: T", "order :: AtomicOrder = SequentiallyConsistent"}},
    {LSP_BUILTIN_CALLABLE_ATOMIC,
     "fetch_and",
     "fetch_and :: fn (value: T, order :: AtomicOrder = "
     "SequentiallyConsistent) -> T",
     "fetch_and(value: T, order :: AtomicOrder = SequentiallyConsistent) -> T",
     "Atomically applies bitwise AND and returns the previous value.",
     2,
     {"value: T", "order :: AtomicOrder = SequentiallyConsistent"}},
    {LSP_BUILTIN_CALLABLE_ATOMIC,
     "fetch_or",
     "fetch_or :: fn (value: T, order :: AtomicOrder = SequentiallyConsistent) "
     "-> T",
     "fetch_or(value: T, order :: AtomicOrder = SequentiallyConsistent) -> T",
     "Atomically applies bitwise OR and returns the previous value.",
     2,
     {"value: T", "order :: AtomicOrder = SequentiallyConsistent"}},
    {LSP_BUILTIN_CALLABLE_ATOMIC,
     "fetch_xor",
     "fetch_xor :: fn (value: T, order :: AtomicOrder = "
     "SequentiallyConsistent) -> T",
     "fetch_xor(value: T, order :: AtomicOrder = SequentiallyConsistent) -> T",
     "Atomically applies bitwise XOR and returns the previous value.",
     2,
     {"value: T", "order :: AtomicOrder = SequentiallyConsistent"}},
    {LSP_BUILTIN_CALLABLE_ATOMIC,
     "compare_exchange",
     "compare_exchange :: fn (expected: T, desired: T, success_order :: "
     "AtomicOrder = SequentiallyConsistent, failure_order :: AtomicLoadOrder = "
     "SequentiallyConsistent) -> AtomicCompareExchangeResult[T]",
     "compare_exchange(expected: T, desired: T, success_order :: AtomicOrder = "
     "SequentiallyConsistent, failure_order :: AtomicLoadOrder = "
     "SequentiallyConsistent) -> AtomicCompareExchangeResult[T]",
     "Compares with expected, conditionally stores desired, and returns "
     "whether the exchange occurred with the observed value on failure.",
     4,
     {"expected: T",
      "desired: T",
      "success_order :: AtomicOrder = SequentiallyConsistent",
      "failure_order :: AtomicLoadOrder = SequentiallyConsistent"}},
    {LSP_BUILTIN_CALLABLE_ATOMIC,
     "compare_exchange_weak",
     "compare_exchange_weak :: fn (expected: T, desired: T, success_order :: "
     "AtomicOrder = SequentiallyConsistent, failure_order :: AtomicLoadOrder = "
     "SequentiallyConsistent) -> AtomicCompareExchangeResult[T]",
     "compare_exchange_weak(expected: T, desired: T, success_order :: "
     "AtomicOrder = SequentiallyConsistent, failure_order :: AtomicLoadOrder = "
     "SequentiallyConsistent) -> AtomicCompareExchangeResult[T]",
     "Performs a weak compare-exchange that may fail spuriously and returns "
     "the observed value on failure.",
     4,
     {"expected: T",
      "desired: T",
      "success_order :: AtomicOrder = SequentiallyConsistent",
      "failure_order :: AtomicLoadOrder = SequentiallyConsistent"}},

    {LSP_BUILTIN_CALLABLE_ARENA_CONSTRUCTOR,
     "arena",
     "arena :: fn (num_bytes: usize, increment: usize = num_bytes) -> arena",
     "arena(num_bytes: usize, increment: usize = num_bytes) -> arena",
     "Creates a pointer-stable arena with the requested initial capacity. The "
     "optional increment controls how much storage is committed when more "
     "space is needed.",
     2,
     {"num_bytes: usize", "increment: usize = num_bytes"}},
};

const LspBuiltinCallable* lsp_builtin_callable(LspBuiltinCallableOwner owner,
                                               string                  name)
{
    for (u32 i = 0;
         i < sizeof(lsp_builtin_callables) / sizeof(lsp_builtin_callables[0]);
         ++i) {
        const LspBuiltinCallable* callable = &lsp_builtin_callables[i];
        if (callable->owner == owner && string_eq_cstr(name, callable->name)) {
            return callable;
        }
    }
    return NULL;
}
