use std.io

Point :: plex #c {
    x    i32
    y    i32
    name string
}

Packed :: plex #packed {
    a u8
    b i32
}

main :: fn () {
    p := Point { x: 1, y: 2, name: "first" }
    q := p with { y: 7, name: "second" }
    pp := ^q
    prn($"{pp.name} {pp.x} {pp.y}")
    _packed := Packed { a: 1, b: 2 }
}
¬
[
    {
        "jsonrpc": "2.0",
        "id": 2,
        "method": "textDocument/semanticTokens/full",
        "params": {
            "textDocument": {
                "uri": "file:///test.n"
            }
        }
    }
]
¬
[
    {
        "jsonrpc": "2.0",
        "id": 1,
        "result": {
            "serverInfo": {
                "name": "Nerd LSP",
                "version": "0.1.0"
            },
            "capabilities": {
                "textDocumentSync": {
                    "openClose": true,
                    "change": 2
                },
                "hoverProvider": true,
                "definitionProvider": true,
                "documentSymbolProvider": true,
                "completionProvider": {
                    "triggerCharacters": [
                        "."
                    ],
                    "resolveProvider": false
                },
                "semanticTokensProvider": {
                    "legend": {
                        "tokenTypes": [
                            "variable",
                            "function",
                            "keyword",
                            "number",
                            "operator",
                            "string"
                        ],
                        "tokenModifiers": []
                    },
                    "full": true
                }
            }
        }
    },
    {
        "jsonrpc": "2.0",
        "method": "textDocument/publishDiagnostics",
        "params": {
            "uri": "file:///test.n",
            "diagnostics": []
        }
    },
    {
        "jsonrpc": "2.0",
        "id": 2,
        "result": {
            "data": [
                0,
                0,
                3,
                2,
                0,
                0,
                4,
                3,
                0,
                0,
                0,
                3,
                1,
                4,
                0,
                0,
                1,
                2,
                0,
                0,
                2,
                0,
                5,
                0,
                0,
                0,
                6,
                1,
                4,
                0,
                0,
                1,
                1,
                4,
                0,
                0,
                2,
                4,
                2,
                0,
                0,
                6,
                1,
                0,
                0,
                1,
                4,
                1,
                0,
                0,
                0,
                5,
                3,
                0,
                0,
                1,
                4,
                1,
                0,
                0,
                0,
                5,
                3,
                0,
                0,
                1,
                4,
                4,
                0,
                0,
                0,
                5,
                6,
                0,
                0,
                3,
                0,
                6,
                0,
                0,
                0,
                7,
                1,
                4,
                0,
                0,
                1,
                1,
                4,
                0,
                0,
                2,
                4,
                2,
                0,
                0,
                6,
                6,
                0,
                0,
                1,
                4,
                1,
                0,
                0,
                0,
                2,
                2,
                0,
                0,
                1,
                4,
                1,
                0,
                0,
                0,
                2,
                3,
                0,
                0,
                3,
                0,
                4,
                1,
                0,
                0,
                5,
                1,
                4,
                0,
                0,
                1,
                1,
                4,
                0,
                0,
                2,
                2,
                2,
                0,
                1,
                4,
                1,
                0,
                0,
                0,
                2,
                1,
                4,
                0,
                0,
                3,
                5,
                0,
                0,
                0,
                8,
                1,
                0,
                0,
                0,
                1,
                1,
                4,
                0,
                0,
                2,
                1,
                3,
                0,
                0,
                3,
                1,
                0,
                0,
                0,
                1,
                1,
                4,
                0,
                0,
                2,
                1,
                3,
                0,
                0,
                3,
                4,
                0,
                0,
                0,
                4,
                1,
                4,
                0,
                0,
                2,
                7,
                5,
                0,
                1,
                4,
                1,
                0,
                0,
                0,
                2,
                1,
                4,
                0,
                0,
                3,
                1,
                0,
                0,
                0,
                2,
                4,
                2,
                0,
                0,
                7,
                1,
                0,
                0,
                0,
                1,
                1,
                4,
                0,
                0,
                2,
                1,
                3,
                0,
                0,
                3,
                4,
                0,
                0,
                0,
                4,
                1,
                4,
                0,
                0,
                2,
                8,
                5,
                0,
                1,
                4,
                2,
                0,
                0,
                0,
                3,
                1,
                4,
                0,
                0,
                4,
                1,
                0,
                0,
                1,
                4,
                3,
                1,
                0,
                0,
                4,
                2,
                5,
                0,
                0,
                3,
                2,
                0,
                0,
                0,
                2,
                1,
                4,
                0,
                0,
                1,
                4,
                0,
                0,
                0,
                5,
                1,
                5,
                0,
                0,
                2,
                2,
                0,
                0,
                0,
                2,
                1,
                4,
                0,
                0,
                1,
                1,
                0,
                0,
                0,
                2,
                1,
                5,
                0,
                0,
                2,
                2,
                0,
                0,
                0,
                2,
                1,
                4,
                0,
                0,
                1,
                1,
                0,
                0,
                0,
                2,
                1,
                5,
                0,
                1,
                4,
                7,
                0,
                0,
                0,
                8,
                1,
                4,
                0,
                0,
                3,
                6,
                0,
                0,
                0,
                9,
                1,
                0,
                0,
                0,
                1,
                1,
                4,
                0,
                0,
                2,
                1,
                3,
                0,
                0,
                3,
                1,
                0,
                0,
                0,
                1,
                1,
                4,
                0,
                0,
                2,
                1,
                3,
                0
            ]
        }
    },
    {
        "jsonrpc": "2.0",
        "id": 999,
        "result": null
    }
]
